// @ts-nocheck
// src/app/api/admin/backfill-recurring-schedules/route.ts
//
// One-off repair tool for the two gaps fixed in this same change: the admin
// booking EDIT branch and the voice/Aria booking path both used to store
// `jobs.frequency` as an inert label without ever creating the
// `recurring_schedules` row the materializer actually reads. Any job created
// through either of those paths before this fix is a "phantom recurring
// booking" — it looks recurring in the calendar/job view, the customer
// believes they're on a regular schedule, but nothing ever generates the
// following occurrences. This is what caused customers to be silently missed.
//
// This route finds exactly those jobs (frequency set to a recurring value,
// no recurring_schedule_id, and not itself already generated by a schedule)
// scoped to the caller's own business, and — only on POST — creates the
// missing schedule for each one, anchored to that job's own scheduled_at,
// then materializes immediately so future occurrences appear right away.
//
// GET is a dry run: it reports what would be created without writing anything,
// so this can be checked before it's actually run.
import { NextRequest, NextResponse } from 'next/server'
import { createClient } from '@/lib/supabase/server'
import { createAdminClient } from '@/lib/supabase/admin'
import { getNextDate, materializeRecurringJobs } from '@/lib/recurring/materialize'

const RECURRING_FREQUENCIES = ['weekly', 'fortnightly', 'monthly']

async function findOrphans(admin: ReturnType<typeof createAdminClient>, businessId: string) {
  const { data: jobs, error } = await admin
    .from('jobs')
    .select('id, customer_id, service_id, address_id, provider_id, frequency, scheduled_at, price, total_price, payment_method, notes, status, customer:customers(full_name, email, phone)')
    .eq('business_id', businessId)
    .in('frequency', RECURRING_FREQUENCIES)
    .is('recurring_schedule_id', null)
    .neq('status', 'cancelled')
    .order('scheduled_at', { ascending: true })

  if (error) throw new Error(error.message)
  return jobs || []
}

async function requireBusiness(request: NextRequest) {
  const supabase = createClient()
  const { data: { user } } = await supabase.auth.getUser()
  if (!user) return { error: NextResponse.json({ error: 'Unauthorized' }, { status: 401 }) }

  const admin = createAdminClient()
  const { data: profile } = await admin.from('profiles').select('business_id').eq('id', user.id).single()
  if (!profile?.business_id) return { error: NextResponse.json({ error: 'Unauthorized' }, { status: 401 }) }

  return { admin, businessId: profile.business_id }
}

// Dry run — lists the jobs that would get a schedule created, no writes.
export async function GET(request: NextRequest) {
  const ctx = await requireBusiness(request)
  if ('error' in ctx) return ctx.error
  const { admin, businessId } = ctx

  const orphans = await findOrphans(admin, businessId)
  return NextResponse.json({
    dry_run: true,
    count: orphans.length,
    jobs: orphans.map(j => ({
      id: j.id,
      customer_name: j.customer?.full_name,
      customer_email: j.customer?.email,
      frequency: j.frequency,
      scheduled_at: j.scheduled_at,
      status: j.status,
    })),
  })
}

// Actually creates the missing recurring_schedules rows and materializes.
export async function POST(request: NextRequest) {
  const ctx = await requireBusiness(request)
  if ('error' in ctx) return ctx.error
  const { admin, businessId } = ctx

  const orphans = await findOrphans(admin, businessId)
  const results: any[] = []

  for (const job of orphans) {
    try {
      const nextOccurrence = getNextDate(new Date(job.scheduled_at), job.frequency)
      const { data: scheduleRow, error: scheduleErr } = await admin
        .from('recurring_schedules')
        .insert({
          business_id: businessId,
          customer_id: job.customer_id,
          service_id: job.service_id,
          address_id: job.address_id,
          provider_id: job.provider_id ?? null,
          frequency: job.frequency,
          next_scheduled_at: nextOccurrence.toISOString(),
          // Anchored to this job's own date — it's the true first occurrence of
          // the series the customer believes they've been on all along.
          anchor_date: new Date(job.scheduled_at).toISOString(),
          is_active: true,
          price: job.price,
          auto_charge: (job.payment_method ?? 'card') === 'card',
          notes: job.notes ?? null,
        })
        .select('id')
        .single()

      if (scheduleErr) {
        results.push({ job_id: job.id, customer: job.customer?.full_name, ok: false, error: scheduleErr.message })
        continue
      }

      await admin.from('jobs').update({ recurring_schedule_id: scheduleRow.id }).eq('id', job.id)
      results.push({ job_id: job.id, customer: job.customer?.full_name, ok: true, schedule_id: scheduleRow.id })
    } catch (e: any) {
      results.push({ job_id: job.id, customer: job.customer?.full_name, ok: false, error: e.message })
    }
  }

  const materializeResult = await materializeRecurringJobs(admin, { businessId })

  return NextResponse.json({
    schedules_created: results.filter(r => r.ok).length,
    schedules_failed: results.filter(r => !r.ok).length,
    results,
    materialize: materializeResult,
  })
}
